Subscribe to HANDLE_METHOD_ALL
sciter-sdk/rust-sciter pull request #98
Opened 2021-02-19 06:21 UTC by GirkovArpa

This is required for `Window.this.xcall(native_function_name, ...arguments)` with Sciter.JS

2021-04-06 14:34 UTC, SonnyX commented
At the very least this misses an update to the documentation above the member itself, can you also explain if this has other implications for non-SciterJS users?

2021-04-06 14:34 UTC, SonnyX requested changes

2021-04-06 14:34 UTC, SonnyX commented on src/dom.rs
>  	/// Default is `HANDLE_BEHAVIOR_EVENT | HANDLE_SCRIPTING_METHOD_CALL` which covers behavior events
Misses an update to this documentation

2021-04-09 20:30 UTC, GirkovArpa commented
I am not sure about implications for Sciter.TIS users.

2021-04-09 20:30 UTC, closed without merging